[project]
name = "protoc-gen-grpc-py"
version = "0.2.0"
description = ""
readme = "README.md"
requires-python = ">=3.10"
license = "Apache-2.0"
license-files = ["LICENSE"]
keywords = ["grpc", "protobuf", "rpc"]
classifiers = [
  "Development Status :: 4 - Beta",
  "Environment :: Console",
  "Environment :: Plugins",
  "Intended Audience :: Developers",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Programming Language :: Python :: Free Threading",
  "Topic :: File Formats",
  "Topic :: Software Development :: Code Generators",
]
dependencies = [
  "protobuf-py==0.2.0",
]

[project.urls]
Documentation = "https://protobufpy.com/"
Homepage = "https://github.com/bufbuild/protoc-gen-grpc-py"
Issues = "https://github.com/bufbuild/protoc-gen-grpc-py/issues"
Source = "https://github.com/bufbuild/protoc-gen-grpc-py"

[project.scripts]
protoc-gen-grpc-py = "protoc_gen_grpc_py:main"

[dependency-groups]
dev = [
  "example",

  "buf-bin==1.72.0",
  "grpcio==1.82.1",
  "poethepoet==0.48.0",
  "protoc-gen-py==0.2.0",
  "pytest==9.1.1",
  "pytest-asyncio==1.4.0",
  "ruff==0.15.22",
  "tombi==1.2.4",
  "ty==0.0.62",
  "types-grpcio==1.82.1.20260711",
]

docs = ["mkdocstrings-python==2.0.5", "zensical==0.0.51"]

[build-system]
requires = ["uv_build>=0.11.2,<0.12"]
build-backend = "uv_build"

[tool.pytest.ini_options]
asyncio_mode = "strict"
asyncio_default_fixture_loop_scope = "module"
asyncio_default_test_loop_scope = "module"

[tool.uv.sources]
example = { workspace = true }
protoc-gen-grpc-py = { workspace = true }

[tool.uv.workspace]
members = [
  "example",
]
