name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

permissions:
  contents: read

jobs:
  test:
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        runner:
          - ubuntu-24.04
          - macos-15
          - windows-2025

        # We don't test on 3.14t yet because grpcio doesn't publish wheels for it
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install uv with Python ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          version: "0.12.7"
          python-version: ${{ matrix.python-version }}

      - run: uv sync --locked

      - run: uv run poe test

  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          version: "0.12.7"
          python-version: "3.10"

      - run: uv sync --locked

      - run: uv run poe lint

      - run: uv run poe format

      - run: uv run poe checkgenerate
